version: "3.8"

networks:
  app-tier:
    driver: bridge

services:
  # transcoder:
  #   # platform: linux/amd64
  #   image: thanhan201/transcoder:2.0.0
  #   # build:
  #   #   context: ./
  #   #   dockerfile: ./apps/transcoder/Dockerfile
  #   #   target: development
  #   env_file:
  #     - .env
  #   ports:
  #     - 8081:8081
  #   # depends_on:
  #   # - redis
  #   # - rabbitmq
  #   # - postgres
  #   volumes:
  #     - .:/usr/src/app # any change to base folder should be reflected
  #     - /usr/src/app/node_modules
  #   # command: npm run start:dev transcoder # overrides CMD from dockerfile
  #   networks:
  #     - app-tier

  api:
    platform: linux/amd64
    # image: api:1.0.0
    container_name: api
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    # depends_on:
    #   - redis_database
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    # networks:
    #   - app-tier

  # redis_database:
  #   image: redis:7.2.4
  #   container_name: redis
  #   restart: unless-stopped
  #   ports:
  #     - 6379:6379
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
  #   # networks:
  #   #   - app-tier

  # imgproxy:
  #   image: darthsim/imgproxy
  #   ports:
  #     - "8081:8080"
  nginx:
    image: nginx:1.25.3
    container_name: nginx
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./ssl:/ssl
    # depends_on:
    #   api:
    #     condition: service_started
    # networks:
    #   - node-network
