version: "3.8"

networks:
  app-tier:
    driver: bridge

services:
  transcoder:
    image: transcoder:version1
    # build:
    #   context: ./
    #   dockerfile: ./apps/transcoder/Dockerfile
    #   target: development
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - redis
      # - rabbitmq
      # - postgres
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    # command: npm run start:dev transcoder # overrides CMD from dockerfile
    # command: node dist/apps/transcoder/apps/transcoder/src/main # overrides CMD from dockerfile
    networks:
      - app-tier

  # api:
  #   build:
  #     context: ./
  #     dockerfile: ./apps/api/Dockerfile
  #   ports:
  #     - '4000:5000'
  #   env_file:
  #     - .env
  #   depends_on:
  #     #   - rabbitmq
  #     - transcoder
  #     #   - presence
  #   volumes:
  #     - .:/usr/src/app # any change to base folder should be reflected
  #     - /usr/src/app/node_modules
  #   command: npm run start:dev api

  redis:
    image: redis:7.2.4
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
  # healthcheck:
  #   test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
  # networks:
  #   - node-network

  # redis:
  #   image: redis
  #   command: /bin/sh -c "redis-server --requirepass $$REDIS_PASS"
  #   env_file:
  #     - .env
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ./redis/data:/data
