FROM nginx:1.25.3
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
# COPY localhost.crt /etc/nginx/ssl-certificate/localhost.crt
# COPY localhost.key /etc/nginx/ssl-certificate/localhost.key
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]